"""Shared workstation core package.

This package defines cross-environment foundations that can be reused by
multiple AWS workstation applications.
"""

from workstation_core.ami_lifecycle import (
    AmiModeConfig,
    AmiSelectionResult,
    build_ami_lookup_error_message,
    create_image_from_instance,
    is_truthy,
    list_environment_images,
    pick_image_interactively,
    read_ami_mode_from_env,
    resolve_ami_selection,
    resolve_exact_image_id,
    resolve_running_instance_id,
    run_ami_permission_preflight,
    validate_mode_arguments,
    wait_for_image_available,
)
from workstation_core.cdk_helpers import (
    CdkTarget,
    build_bootstrap_user_data,
    build_spot_fleet_launch_specification,
    build_stack_name,
    resolve_ami_id,
    resolve_subnet_availability_zone,
)
from workstation_core.config import CoreConfig
from workstation_core.environment_config import (
    AmiSelectorConfig,
    EnvironmentSpec,
    validate_environment_spec,
)
from workstation_core.orchestration import (
    DeployWorkflowInputs,
    OrchestrationPlan,
    StopOrchestrationInputs,
    build_stop_image_name,
    deploy_stack,
    load_environment_spec,
    make_ec2_client,
    parse_stop_ami_config,
    run_command,
    run_deploy_lifecycle,
    run_post_deploy_check,
    run_stop_orchestration,
    validate_plan,
)
from workstation_core.runtime import RuntimeContext
from workstation_core.runtime_resolution import (
    get_account,
    get_profile_name,
    get_profile_section_name,
    get_region,
    get_region_from_config,
    load_aws_config,
    parse_optional_bool_context,
    parse_optional_text_context,
)
from workstation_core.interactive_workstation import (
    ActionResult,
    EnvironmentTarget,
    choose_environment,
    discover_environments,
    dispatch_action,
    load_last_used_environment_key,
    parse_action_choice,
    run_script,
    save_last_used_environment_key,
)
from workstation_core.workstation_status import WorkstationStatus, get_workstation_status

__all__ = [
    "AmiSelectorConfig",
    "AmiModeConfig",
    "AmiSelectionResult",
    "CdkTarget",
    "CoreConfig",
    "DeployWorkflowInputs",
    "EnvironmentSpec",
    "OrchestrationPlan",
    "StopOrchestrationInputs",
    "RuntimeContext",
    "build_ami_lookup_error_message",
    "build_bootstrap_user_data",
    "build_spot_fleet_launch_specification",
    "build_stack_name",
    "deploy_stack",
    "resolve_ami_id",
    "resolve_subnet_availability_zone",
    "validate_environment_spec",
    "is_truthy",
    "list_environment_images",
    "load_environment_spec",
    "make_ec2_client",
    "pick_image_interactively",
    "read_ami_mode_from_env",
    "resolve_ami_selection",
    "resolve_exact_image_id",
    "run_ami_permission_preflight",
    "run_command",
    "run_deploy_lifecycle",
    "run_post_deploy_check",
    "validate_plan",
    "build_stop_image_name",
    "parse_stop_ami_config",
    "run_stop_orchestration",
    "validate_mode_arguments",
    "resolve_running_instance_id",
    "create_image_from_instance",
    "wait_for_image_available",
    "get_account",
    "get_profile_name",
    "get_profile_section_name",
    "get_region",
    "get_region_from_config",
    "load_aws_config",
    "parse_optional_bool_context",
    "parse_optional_text_context",
    "ActionResult",
    "EnvironmentTarget",
    "choose_environment",
    "discover_environments",
    "dispatch_action",
    "load_last_used_environment_key",
    "parse_action_choice",
    "run_script",
    "save_last_used_environment_key",
    "WorkstationStatus",
    "get_workstation_status",
]
